### ISSUE TITLE
Im getting an error when launching with optifabric

### ISSUE THREAD

**Issue by noahnao** [Chocohead/OptiFabric#196] opened 2021-03-27 00:27 UTC
I run Sodium for drastic performance improvements, but I want better grass from optifine. I downloaded Optifabric to have the performance from Sodium and better grass, but it gives me an error message, with sodium and Optifabric interfering. This is likely due to the two mods working in the same way. Is there any way I can run them both, or get Better Grass in another way?
If not, I hope you consider adding support for Sodium. If you do I suggest that you let sodium do the heavy lifting because it is more optimized than Optifine, whilst letting Optifine add more customizability and features.
![Udklip](https://user-images.githubusercontent.com/81416193/112704635-983ad680-8e9b-11eb-89b9-1a2478d5de11.PNG)

**Comment by lartts** [comment] 2021-03-27 14:14
Sodium does not work with Optifine, read the Curseforge page of the Sodium mod

**Comment by Chocohead** [comment] 2021-05-28 20:27
Duplicate of #40

**Closed as completed by Chocohead** 2021-05-28 20:27 UTC
