### ISSUE TITLE
MOD

### ISSUE THREAD

**Issue by J-a-y-d-y** [Chocohead/OptiFabric#358] opened 2021-08-29 03:16 UTC
Doesn't work with the lambda controller mod. It crashes immediately and you can't play. witch sucks because im on a laptop because my desktop is packed as I am in between places. so I use a controller :/ Please fix it sooooon.

**Comment by MissGamerz** [comment] 2021-08-31 16:15
seems like a incompatibility with optifine and that MOD nothing to do with optifabric.....

**Comment by Chocohead** [comment] 2021-10-11 21:19
Duplicate of #51

**Closed as completed by Chocohead** 2021-10-11 21:19 UTC
Labels: Duplicate
