### ISSUE TITLE
Crashes with Lambdacontrol mod

### ISSUE THREAD

**Issue by Computerlabrat** [Chocohead/OptiFabric#174] opened 2021-03-01 20:20 UTC
I'm not sure if this has been posted, but I'm using Optifabric with what is currently the latest version of Optifine and the game refuse to launch when I try to use Optifabric with lambdacontrols-fabric-1.5.0+1.16.2. Can you look into this for me, please?
Thank you for your time.

**Comment by Chocohead** [comment] 2021-03-02 01:20
Duplicate of #51

**Closed as completed by Chocohead** 2021-03-02 01:20 UTC
