### ISSUE TITLE
pls  

### ISSUE THREAD

**Issue by sebasssss627y** [Chocohead/OptiFabric#218] opened 2021-05-18 14:13 UTC
java.lang.RuntimeException: Failed to remap jar
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:171)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:156)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:117)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at com.chocohead.mm.Plugin$$Lambda$73/250112971.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.EntrypointStorage$$Lambda$64/818493590.get(Unknown Source)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at me.deftware.client.framework.main.Main.main(Main.java:43)
Caused by: java.nio.file.FileSystemException: C:\Users\Acer\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\zipfstmp2726562822048293193.tmp -> C:\Users\Acer\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-lambdafix.jar: Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at com.sun.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1297)
	at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:277)
	at net.fabricmc.tinyremapper.OutputConsumerPath.close(OutputConsumerPath.java:315)
	at me.modmuss50.optifabric.mod.OptifineSetup.remapOptifine(OptifineSetup.java:170)
	... 31 more

**Comment by Chocohead** [comment] 2021-06-02 01:48
Duplicate of #188

**Closed as completed by Chocohead** 2021-06-02 01:48 UTC
