### ISSUE TITLE
1.17 crash with optifabric and architectury, cloth-api, cloth-config and light-overlay

### ISSUE THREAD

**Issue by Gxinz** [Chocohead/OptiFabric#259] opened 2021-06-15 17:29 UTC
When i try to start Fabric with optifabric and architectury, cloth-api, cloth-config and light-overlay it crashes.

![mods](https://user-images.githubusercontent.com/85958679/122098036-9fc1aa00-ce10-11eb-9a7a-0a44ecfda6cd.png)

Crash Code: https://pastebin.com/pjDCxJi8

**Comment by semicolonmystery** [comment] 2021-06-15 21:26
Same problem.

**Comment by gonka26** [comment] 2021-06-17 14:03
Same. I can't open optifabric and REI on same time :/

**Comment by pfiszer** [comment] 2021-06-17 14:46
same problem

**Comment by awbuckst11181999** [comment] 2021-06-18 00:07
same problem, incompatibility seems to come from architextury

**Comment by joshbarrass** [comment] 2021-06-18 19:33
Can confirm getting the same problem, and that the issue seems to be Architectury as @awbuckst11181999 says (loads with cloth config, does not load with architectury without light-overlay, error message seems to reference architectury as well)

**Comment by evolvoodoo** [comment] 2021-06-18 22:03
I am also seeing this issue with Architectury and Optifabric together. Either separate work fine.

**Comment by joshbarrass** [comment] 2021-06-19 02:16
Yes that is what I meant @evolvoodoo, apologies if that wasn't clear.

Until a fix is released officially, the builds provided in [this pull request](https://github.com/Chocohead/OptiFabric/pull/246) are working as a solution. [1.11.3f](https://github.com/Chocohead/OptiFabric/files/6674174/optifabric-1.11.3f.unzip.me.zip) is working for me (though bear in mind these are dev builds, so use at your own risk)

**Comment by Chocohead** [comment] 2021-06-20 02:39
Duplicate of #238

**Closed as completed by Chocohead** 2021-06-20 02:39 UTC
