### ISSUE TITLE
Incompatible with Roughly Enough Item

### ISSUE THREAD

**Issue by Mooonblaze** [Chocohead/OptiFabric#250] opened 2021-06-13 20:15 UTC
Game will not launch with REI installed. I believe it is a direct incompatibility with Architectury which is a required lib for REI. (Sorry about the edits, I keep accidentally hitting the enter button and posting.)

**Comment by cs127** [comment] 2021-06-14 08:21
Duplicate of #244

**Comment by Chocohead** [comment] 2021-06-20 02:38
Duplicate of #238

**Closed as completed by Chocohead** 2021-06-20 02:38 UTC
