### ISSUE TITLE
OptiFabric not working with Fabric 0.12.5

### ISSUE THREAD

**Issue by MajiCoder** [Chocohead/OptiFabric#465] opened 2021-11-25 02:01 UTC
Simple: I installed the latest fabric (0.12.5), fabric api, optifine, and optifabric. But when I try to start mc, the game crashes, saying that optifabric only supports 0.8 - 0.12, and so 0.12.5 is not supported. The curseforge page said that optifabric supported every new fabric release?

Full message:
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.9 (C:\Users\Ezekiel\AppData\Roaming\.minecraft\mods\optifabric-1.11.9.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\Ezekiel\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.9, reason: to remove
	 - mod 'Manningham Mills' (mm) 2.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by fayearth** [comment] 2021-11-25 08:13
Update your optifabric to 1.12.5

**Comment by MajiCoder** [comment] 2021-11-25 17:04
It says that version of 1.12.5 is 1.17.1 though? I'm trying to use MC version 1.16.5 ??

**Comment by fayearth** [comment] 2021-11-26 06:09
1.12.5 for version 1.16.5 is in CF

**Comment by Chocohead** [comment] 2021-11-27 02:02
Duplicate of #394

The OptiFabric versions are backwards compatible (at the moment at least), so if you really wanted you could use OptiFabric v1.12.5 all the way back to 1.16.1

**Closed as completed by Chocohead** 2021-11-27 02:02 UTC
