### ISSUE TITLE
Incompatible with RoughlyEnoughItemsFabric 

### ISSUE THREAD

**Issue by SleazzyRat** [Chocohead/OptiFabric#255] opened 2021-06-15 03:53 UTC
I experience crashing when running Optifabric 1.11.1 ( with preview_Optifine 1.17_HD_U_G9_pre21 ) and RoughlyEnoughItems-6.0251-alpha-fabric. I dont get a crash report or anything just Exit Code:0 . Hopefully not to hard to fix, looking forward to an update. Thx for your time
![image](https://user-images.githubusercontent.com/85917655/121990239-abeb3000-cd5a-11eb-85ff-6ad88ff8eaa4.png)
![image](https://user-images.githubusercontent.com/85917655/121990337-d63ced80-cd5a-11eb-888d-6b8263528e19.png)

**Comment by cs127** [comment] 2021-06-15 08:40
Duplicate of #244

**Comment by Chocohead** [comment] 2021-06-20 02:39
Duplicate of #238

**Closed as completed by Chocohead** 2021-06-20 02:39 UTC
