### ISSUE TITLE
Problems with either Architectury or rei(Note: this is mainly for awareness of the priority)

### ISSUE THREAD

**Issue by emeraldran** [Chocohead/OptiFabric#252] opened 2021-06-14 17:10 UTC
ok I know I will get a lot of criticism but so this optifabric is not working with Architectury it looks like in the launcher log but so Architectury should have been fixed by now because it is a core mod for a lot of fabric mods. rei isnt the only one that relies on it but bits and chisels do too I believe and if someone can update me on that bug fix with architectury

**Comment by Chocohead** [comment] 2021-06-20 02:38
Duplicate of #238

**Closed as completed by Chocohead** 2021-06-20 02:38 UTC
