### ISSUE TITLE
OptiFabric has incompatible with Minecraft 1.16.5

### ISSUE THREAD

**Issue by Triheron** [Chocohead/OptiFabric#151] opened 2021-01-16 05:27 UTC
Latest OptiFabric has incompatible with Minecraft 1.16.5. Can you fix it?

**Comment by Andre601** [comment] 2021-01-16 13:38
Since the only real changes in 1.16.5 are fixes to server and client crashing bugs, should it probably be enough to just add `1.16.5` to `depends.minecraft`
https://github.com/Chocohead/OptiFabric/blob/llama/src/main/resources/fabric.mod.json#L36

**Comment by gnsc4** [comment] 2021-01-17 04:27
If this is our first time installing it where do we put the file? (The Json)

**Comment by mangotango69202** [comment] 2021-01-17 06:35
c this tutorial i made 

https://drive.google.com/file/d/1BEZw8etRYegEpT3Sv9O-Co7h-MzFNQjX/view?usp=sharing

**Comment by IMS212** [comment] 2021-01-17 06:55
the json goes inside the jar file (jar files are just renamed zip files)

**Comment by mangotango69202** [comment] 2021-01-17 07:05
this is a step by step 
(you will need to have wirar installed)
first open your folder where optifine fabric is located (likely the mods folder) 

create a new folder in that folder name it anything you want (its a temp folder we will delete after we are done)

move the optifine fabric into that temp folder 

right click on the optifine fabric and select extract files here

so you will see so mnay files come open the fabric.mod.json

in that go to depends and add 1.16.5 like this

https://pastebin.com/raw/NZzAWRjU

now save it and then select every thing in that temp folder you made except the optifine fabric jar

make archive it into a zip/rar format 

go to this website

if you made into zip https://convertio.co/zip-jar/

if rar https://convertio.co/rar-jar/

now upload it and wait for it to convert and done download it put it into mods folder

**Comment by gnsc4** [comment] 2021-01-17 09:07
> this is a step by step
> (you will need to have wirar installed)
> first open your folder where optifine fabric is located (likely the mods folder)
> 
> create a new folder in that folder name it anything you want (its a temp folder we will delete after we are done)
> 
> move the optifine fabric into that temp folder
> 
> right click on the optifine fabric and select extract files here
> 
> so you will see so mnay files come open the fabric.mod.json
> 
> in that go to depends and add 1.16.5 like this
> 
> https://pastebin.com/raw/NZzAWRjU
> 
> now save it and then select every thing in that temp folder you made except the optifine fabric jar
> 
> make archive it into a zip/rar format
> 
> go to this website
> 
> if you made into zip https://convertio.co/zip-jar/
> 
> if rar https://convertio.co/rar-jar/
> 
> now upload it and wait for it to convert and done download it put it into mods folder

This worked perfectly thank you very much 👍

**Comment by adamkee97** [comment] 2021-01-18 03:03
I have another method if you have 7-Zip and is familiar with it: 

1. Download `optifabric-1.8.16.jar` from [https://www.curseforge.com/minecraft/mc-mods/optifabric/files](url). 
2. Open the file with 7-Zip. 
3. In 7-Zip, right-click on `fabric.mod.json` and choose **Edit**. 
4. Add `"1.16.5"` into the file, and do not forget to add a `,` (comma) to `"1.16.4"`

```
  "depends": {
    "fabricloader": "\u003e\u003d0.8.0",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4",
      "1.16.5"
    ],
    "mm": "\u003e\u003d2.0"
  },
```

5. Save the file and close the text editor. 
6. 7-Zip will ask whether you want to "update it in the archive", click OK. 
7. Now, the new JAR file should be ready.

**Comment by kyrkis** [comment] 2021-01-18 11:40
Im a bit confused I got most of that to work. I saved the text and closed notepad but i got no sort of notification about "When 7-Zip asks whether you want to "update it in the archive", click OK." And closing it left it as a folder and not as a jar file. Im confused how to make it into a jar

**Comment by CainSakura** [comment] 2021-01-18 16:48
> Im a bit confused I got most of that to work. I saved the text and closed notepad but i got no sort of notification about "When 7-Zip asks whether you want to "update it in the archive", click OK." And closing it left it as a folder and not as a jar file. Im confused how to make it into a jar

Maybe you extracted the JAR file, and go inside extracted folder, edit, that's not quite right.

You should use 7zip to open the JAR file directly, go find the file inside the JAR, right click, Edit, and save. Since then 7zip will ask you to update.

**Comment by adamkee97** [comment] 2021-01-19 04:05
> I'm a bit confused I got most of that to work. I saved the text and closed notepad but I got no sort of notification about "When 7-Zip asks whether you want to "update it in the archive", click OK." And closing it left it as a folder and not as a jar file. I'm confused how to make it into a jar

@kyrkis Really? That's weird. 7-Zip would not extract/unzip anything unless you specify that to 7-Zip. 

Of course, you can turn that folder into a ZIP file and convert it to JAR file using online services provided by @gnsc4.

**Comment by FarkasJoseph** [comment] 2021-01-19 13:29
If you guys are having issues here is a modified jar (in a zip, extract the zip).
[optifabric-1.8.16patched.zip](https://github.com/Chocohead/OptiFabric/files/5836134/optifabric-1.8.16patched.zip)
Thanks to https://github.com/Chocohead/OptiFabric/issues/155#issuecomment-762479449

**Comment by Kazlehoff** [comment] 2021-01-19 21:53
Open the jar with 7zip. extract optifabric.mod.json.
find where it lists the versions. add 1.16.5

im up and running and its fine.

**Comment by Turphin** [comment] 2021-01-20 02:05
use 7-zip or winrar to extract the jar to a folder (make sure it's using the `extract to optifabric-[version]\` option if using the windows shell right-click menu options) and then update the json (instructions below), delete everything in the jar (keep a file in there temporarily so it doesn't delete the jar and name it something like `deleteme` so you know which file to delete after), and copy the contents of the extracted folder into the empty jar and delete your temporary file. if you feel like it, you can make a separate jarfile and copy everything into it, or alternatively, drag the json out of the jar, delete the json still in the jar, update the extracted json, and drag the json back into the jar. optifabric should now work as intended.



area to edit: 
open the file named `fabric.mod.json` (use any text editing tool, i use visual studio code, but the default notepad program works too if you don't want to install extra software)

modify this section :
```
"depends": {
    "fabricloader": "\u003e\u003d0.8.0",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4"
    ],
    "mm": "\u003e\u003d2.0"
  },
```
add this to the file:
```
"1.16.4",
"1.16.5"
```
the section should now look like this:
```
"depends": {
    "fabricloader": "\u003e\u003d0.8.0",
    "minecraft": [
      "1.16.1",
      "1.16.2",
      "1.16.3",
      "1.16.4",
      "1.16.5"
    ],
    "mm": "\u003e\u003d2.0"
  },
```
>

**Closed as completed** 2021-01-28 00:29 UTC
