### ISSUE TITLE
Found conflicting mods: iris conflicts with {optifabric @ [*]}

### ISSUE THREAD

**Issue by BigBaller27** [Chocohead/OptiFabric#404] opened 2021-10-22 09:13 UTC
Are these mod incompatible and overlap each other, hence making "iris and sodium" conflict with "Optifabric?"

**Comment by Zerphim** [comment] 2021-10-24 09:03
> Are these mod incompatible and overlap each other, hence making "iris and sodium" conflict with "Optifabric?"

I also run this mod with Optifabric and it works for me. What other mods do you have as there may be other incompatibilities?

**Comment by PseudoDistant** [comment] 2021-10-25 23:56
> Are these mod incompatible and overlap each other, hence making "iris and sodium" conflict with "Optifabric?"

Sodium and Iris are both incompatible with OptiFine, so it would stand to reason that they also break OptiFabric...

**Comment by Chocohead** [comment] 2021-11-05 00:00
Duplicate of #359

**Closed as completed by Chocohead** 2021-11-05 00:00 UTC
Labels: Duplicate
