### ISSUE TITLE
Failed to load OptiFine

### ISSUE THREAD

**Issue by WeebBear** [Chocohead/OptiFabric#186] opened 2021-03-08 14:12 UTC
Please help

**Comment by Chocohead** [comment] 2021-03-09 14:23
You're not running two instances of the game at the same time are you? I'd suggest deleting `C:\Users\Madss\Documents\Twitch\Minecraft\Instances\OriginsSMP\.optifine\OptiFine_1.16.5_HD_U_G6\Optifine-lambdafix.jar` (or the entire `.optifine` folder just to make sure nothing else strange happens) and trying again.

**Comment by Chocohead** [comment] 2021-03-10 14:22
Duplicate of #188

**Closed as completed by Chocohead** 2021-03-10 14:22 UTC
