### ISSUE TITLE
Litematica issue version 1.16.2

### ISSUE THREAD

**Issue by Bazoqa** [Chocohead/OptiFabric#11] opened 2020-08-31 02:29 UTC
Litematica works fine without optifine and optifabric, but with the following versions there are rendering issues with litematica schematics, blocks appear diagonal and heavily distorted (even without shaders):

Litematica: litematica-fabric-1.16.2-0.0.0-dev.20200824.031346
Optifine: OptiFine_1.16.2_HD_U_G3
Optifabric: optifabric-1.4.1

Also Misc depencies installed with these:
malilib-fabric-1.16.2-0.10.0-dev.21+arne.1
fabric-api-0.19.0+build.398-1.16

**Comment by Chocohead** [comment] 2020-08-31 23:35
Duplicate of #16

I think this has always been a problem, will mark this as a duplicate of the issue with a picture of the problem.

**Closed as completed by Chocohead** 2020-08-31 23:35 UTC
