### ISSUE TITLE
OptiFine HD U H5 pre4 causes infinite loading Screen

### ISSUE THREAD

**Issue by Chris6ix** [Chocohead/OptiFabric#573] opened 2022-01-09 17:05 UTC
Loading OptiFine HD U H5 pre4 with Fabric (0.12.12-1.18.1) and OptiFabric (1.12.10) causes an infinite loading screen with [this](https://pastebin.com/XdcwW7XN) Error repeating itself over and over again in the logs...

The OptiFine Support said I should report this here...

**Comment by Nuanulla** [comment] 2022-01-11 07:22
Duplicate of #540

**Closed as completed** 2022-02-11 13:51 UTC
