### ISSUE TITLE
Game keeps crashing.

### ISSUE THREAD

**Issue by Tui-Vao** [Chocohead/OptiFabric#125] opened 2020-12-28 15:56 UTC
[crash-2020-12-29_05.23.19-client.txt](https://github.com/Chocohead/OptiFabric/files/5747926/crash-2020-12-29_05.23.19-client.txt)
here is my crash log

**Comment by Chocohead** [comment] 2021-01-08 02:11
Duplicate of #98

**Closed as completed by Chocohead** 2021-01-08 02:11 UTC
