### ISSUE TITLE
Optifabric laods, but newest optifine and preview versions dont.

### ISSUE THREAD

**Issue by KaoVia** [Chocohead/OptiFabric#176] opened 2021-03-03 20:05 UTC
not sure how to attach crash report and such, but optifabric loads and then says that the mods folder has no optifine, but when you do put optifine in the mods folder the game exits upon opening with code 0. 

1.16.5
optifabric version 1.9.6 
optifine version preview_OptiFine_1.16.5_HD_U_G8_pre1, OptiFine HD U G7, OptiFine HD U G6

**Comment by Chocohead** [comment] 2021-03-05 02:48
You can attach the log files directly dragging them into the comment box, or paste them somewhere like [PasteBin](http://pastebin.com) and post a link.

**Comment by KaoVia** [comment] 2021-03-05 10:32
I mean liek where are they located or how to I find them?

**Comment by Permanently** [comment] 2021-03-05 20:20
I also have this error, where Optifine HD U G7 isn't being loaded on 1.16.5, Optifabric version 1.9.6. [Log file here.](https://paste.ee/p/GetZg)

Stack-trace:
```
java.io.UncheckedIOException: Error transforming I:\MultiMC\instances\Forge 1.16.2\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:97)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:97)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:102)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:95)
	... 35 more

```

**Comment by Chocohead** [comment] 2021-03-05 22:50
> 
> 
> I mean liek where are they located or how to I find them?

In the same folder as the `mods` and `config` folders there's `crash-reports` and `logs`. Crash reports and older logs are sorted by date, the newest log files are `latest.log` and possible `debug.log` depending on your launcher.



> 
> 
> I also have this error, where Optifine HD U G7 isn't being loaded on 1.16.5, Optifabric version 1.9.6. [Log file here.](https://paste.ee/p/GetZg)
> 
> Stack-trace:
> 
> ```
> java.io.UncheckedIOException: Error transforming I:\MultiMC\instances\Forge 1.16.2\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar
> 	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:97)
> 	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:97)
> 	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
> 	at java.util.ArrayList.forEach(ArrayList.java:1259)
> 	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
> 	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
> 	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
> 	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> Caused by: java.util.zip.ZipException: error in opening zip file
> 	at java.util.zip.ZipFile.open(Native Method)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
> 	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:102)
> 	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:95)
> 	... 35 more
> ```

If you delete the `I:\MultiMC\instances\Forge 1.16.2\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar` jar does the problem go away? It appears that the OptiFine installer is producing a corrupt zip.

**Comment by Permanently** [comment] 2021-03-06 02:08
> If you delete the `I:\MultiMC\instances\Forge 1.16.2\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar` jar does the problem go away? It appears that the OptiFine installer is producing a corrupt zip.

Seems this did the job!

**Comment by facepalm2333** [comment] 2021-03-23 14:40
Hi,
I use fabric and MutliMC to load optifabric and optifine.
and I follow this tutorial to install optifine on MultiMC

The OptiFine installer requires that MC be installed in the default launcher and has opened the version of MC at least once.  Do this first.
1. Download OptiFine
2. Extract OptiFine 
  a. Double click the download from step 1
  b. Click Extract button
  c. Navigate to MultiMC instance you wish to install OptiFine into (C:\mc\MultiMC\instances\1.13\.minecraft\)
3. Move extracted Optifine to instance \ libraries folder (C:\mc\MultiMC\instances\1.13\libraries\)
4. In MultiMC edit instance, go to Version screen and select the Minecraft entry in the list.  Then click Add to Minecraft.jar
5. Select the OptiFine file you extracted and moved in step 3.
this tutorial is from here:
https://gist.github.com/jspanos71/32dc422eb4435a8f8dd5604e7a77c327


and here are the report:
java.io.UncheckedIOException: Error transforming C:\Users\user\Saved Games\game\minecraft mod\multimc\instances\1.16.5\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:97)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:97)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:667)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:102)
	at me.modmuss50.optifabric.util.ZipUtils.transform(ZipUtils.java:95)
	... 35 more

thank you for reading~

**Comment by Permanently** [comment] 2021-03-23 16:08
Follow [what Chocohead said](https://github.com/Chocohead/OptiFabric/issues/176#issuecomment-791770616) - delete `C:\Users\user\Saved Games\game\minecraft mod\multimc\instances\1.16.5.minecraft.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mod.jar`, and relaunch your game.

**Comment by ghost** [comment] 2021-04-26 11:48
Where that can be found

**Comment by Permanently** [comment] 2021-04-26 18:59
Read the error.

**Comment by Chocohead** [comment] 2021-06-02 01:48
Duplicate of #188

**Closed as completed by Chocohead** 2021-06-02 01:48 UTC

**Comment by Permanently** [comment] 2021-06-02 11:25
mfw an older issue is marked as a duplicate ಠ_ಠ
