### ISSUE TITLE
Incompatible with 1.16.5

### ISSUE THREAD

**Issue by Bruhmoment165** [Chocohead/OptiFabric#155] opened 2021-01-17 20:40 UTC
When I try to launch 1.16.5 fabric launcher it doesn't launch. I think the issue is that optifabric isn't updated to 1.16.5.

**Comment by Titaniumtown** [comment] 2021-01-17 20:42
duplicate.

**Comment by koitsu** [comment] 2021-01-17 22:27
Duplicate of https://github.com/Chocohead/OptiFabric/issues/151 .

**Comment by Bruhmoment165** [comment] 2021-01-18 20:14
I've tried the solutions of issue  #151 but it hasn't worked.  I feel it would be easier if they actually updated to mod for not just but people who discovered optifabric and want to use it.

**Comment by koitsu** [comment] 2021-01-18 21:31
I followed [these instructions](https://github.com/Chocohead/OptiFabric/issues/151#issuecomment-761745580) with success.  Attached here is a fixed `optifabric-1.8.16.jar` (inside of a .zip file) which I made, following those instructions: [optifabric-1.8.16.zip](https://github.com/Chocohead/OptiFabric/files/5832473/optifabric-1.8.16.zip)

**Comment by Bruhmoment165** [comment] 2021-01-19 12:39
I tried using the .zip file but it didn't work. It lets me launch minecraft but I don't get any features of optifine just as when I did it myself. Also, I did convert the .zip file into a jar file.

**Comment by FarkasJoseph** [comment] 2021-01-19 13:27
> I followed [these instructions](https://github.com/Chocohead/OptiFabric/issues/151#issuecomment-761745580) with success. Attached here is a fixed `optifabric-1.8.16.jar` (inside of a .zip file) which I made, following those instructions: [optifabric-1.8.16.zip](https://github.com/Chocohead/OptiFabric/files/5832473/optifabric-1.8.16.zip)

Thank you so much! @Bruhmoment165 you need to EXTRACT the JAR and then put it into your mods with optifine. After that it works splendidly. If you don't trust the zip, just follow the instructions yourself (takes maybe 3 minutes).

**Comment by Bruhmoment165** [comment] 2021-01-19 13:52
@koitsu I was just over complicating things. I was taking the whole .zip file and converting it into a JAR. Thanks for the download it works perfectly fine now. I just extracted the JAR from the .zip file and put it in my mods folder.

**Comment by axalox** [comment] 2021-01-20 10:39
Hello

Please update it for 1.16.5, please please

I can't live without it :)

**Comment by Bruhmoment165** [comment] 2021-01-20 13:02
@koitsu posted a download for 1.16.5 (scroll up)  just download the .zip folder and extract the JAR and put it into your mods folder.

**Comment by Yoosk** [comment] 2021-01-22 15:05
No need to extract any jars or edit mod files, just do it the suggest way for fabric: https://fabricmc.net/wiki/tutorial:dependency_overrides
Just drop this file in the `config` directory and optifabric will work just fine. [fabric_loader_dependencies.json](https://server.yoosk.ovh/fabric_loader_dependencies.json)

**Comment by tim-schmidt** [comment] 2021-01-22 19:19
> No need to extract any jars or edit mod files, just do it the suggest way for fabric: https://fabricmc.net/wiki/tutorial:dependency_overrides
> Just drop this file in the `config` directory and optifabric will work just fine. [fabric_loader_dependencies.json](https://server.yoosk.ovh/fabric_loader_dependencies.json)

**_THIS!_** Thanks so much, @Yoosk!

**Comment by LionZXY** [comment] 2021-01-27 19:32
My crash with this fix:
```
[21:27:06] [main/WARN]: [Indigo] Exception accessing vanilla smooth lighter
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_275]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_275]
	at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.VanillaAoHelper$1.get(VanillaAoHelper.java:56) [54066ac7-f53e-4010-b342-33471981be05.jar:?]
	at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.VanillaAoHelper$1.get(VanillaAoHelper.java:52) [54066ac7-f53e-4010-b342-33471981be05.jar:?]
	at net.fabricmc.fabric.impl.client.indigo.renderer.aocalc.VanillaAoHelper.initialize(VanillaAoHelper.java:67) [54066ac7-f53e-4010-b342-33471981be05.jar:?]
	at net.minecraft.class_778.handler$zzm000$onInit(class_778.java:561) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_778.<init>(class_778.java:68) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_776.<init>(class_776.java:45) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:538) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-fabric-loader-0.11.1-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
[21:27:06] [main/WARN]: [Indigo] Vanilla smooth lighter unavailable. Indigo lighter will be used even if not configured.
[21:27:06] [VersionCheck/INFO]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.16.5/HD_U.txt
[21:27:06] [main/INFO]: Narrator library successfully loaded
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_4696.canRenderInLayer
[21:27:06] [main/INFO]: [OptiFine] *** Reflector Forge ***
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_773.getTexture
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_1299.getTags
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_3611.getTags
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_2791.getWorldForge
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.setKeyConflictContext
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.setKeyModifierAndCode
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_304.getKeyModifier
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_4696.canRenderInLayer
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_3228.isForceTicks
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_5294.getCloudRenderHandler
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_5294.getSkyRenderHandler
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_5294.getWeatherParticleRenderHandler
[21:27:06] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.class_5294.getWeatherRenderHandler
[21:27:06] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
```

Anyone have this problem?

**Closed as completed** 2021-01-28 00:29 UTC
