### ISSUE TITLE
Emissive texture not workin on mc 1.19

### ISSUE THREAD

**Issue by ToxVeszel** [Chocohead/OptiFabric#757] opened 2022-07-04 10:06 UTC
when i place the blocks the emissive textures are not working but when i have it in the hand they work

**Comment by SStatZX** [comment] 2022-07-05 17:17
[As far as I am aware this is an issue caused by optifine and not optifabric,](https://github.com/sp614x/optifine/issues/6854)

At this time it appears emissive textures do not work on optifine regardless if you're using optifabric or not. _(as of pre5)_

**Comment by Chocohead** [comment] 2022-07-23 23:58
This was fixed in OptiFine 1.19_HD_U_H8_pre6

**Closed as completed by Chocohead** 2022-07-23 23:58 UTC
Labels: OptiFine
