### ISSUE TITLE
Fabric with optifine crash

### ISSUE THREAD

**Issue by Whispity** [Chocohead/OptiFabric#474] opened 2021-11-29 07:31 UTC
I get this crash message when i launch fabric on the 0.11.7 loader plus these are the mods in my folder as i would like to run shaders with replay mod
![Screenshot 2021-11-29 182745](https://user-images.githubusercontent.com/94654225/143825850-f5883d04-0c66-48ad-9423-17e90dd8956d.png)
r
![Screenshot 2021-11-29 182727](https://user-images.githubusercontent.com/94654225/143825863-e0644944-47c6-4ed3-b156-7ece86de5526.png)

**Comment by VidTu** [comment] 2021-11-30 14:49
Related to/Duplicate of #389

**Comment by Dracconis** [comment] 2021-11-30 16:33
Can you provide the crash log?

**Comment by Whispity** [comment] 2021-12-01 07:31
> 
[crash-2021-11-29_18.18.42-client.txt](https://github.com/Chocohead/OptiFabric/files/7631692/crash-2021-11-29_18.18.42-client.txt)

**Comment by Dracconis** [comment] 2021-12-01 13:49
Well I can't see why it would be crashing, but I am sure that the dev(s) once they see the crash log will be able to figure it out and tell you what's wrong. Sometimes its not OFa that is the cause and could be on the other end with a different mod. So just wait to see what the Dev(s) say.

**Closed as completed** 2021-12-16 00:16 UTC
