### ISSUE TITLE
Shaders are not compatible with Satin mod

### ISSUE THREAD

**Issue by postal291** [Chocohead/OptiFabric#142] opened 2021-01-08 08:39 UTC
Strange thing is, I'm not using Satin.

Mods:
  [✔️] [1.16.2]bettermodbutton-1.1.4
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] BBOutlineReloaded-2.4-1.16.3-fabric
  [✔️] beenfo-1.16.4-fabric0.25.1-1.3
  [✔️] Blur-2.0.0-1.16.2+fabric
  [✔️] CustomSelectionBox-5.0.2
  [✔️] durabilityviewer-1.16.4-fabric0.25.1-1.9
  [✔️] easierchests-1.16.4-fabric0.25.1-1.6.2
  [✔️] fabric-api-0.28.1+1.16
  [✔️] itemscroller-fabric-1.16.4-0.15.0-dev.20201103.183933
  [✔️] light-overlay-5.5.4
  [✔️] litematica-fabric-1.16.4-0.0.0-dev.20201103.184101
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
  [✔️] minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
  [✔️] modmenu-1.14.13+build.19
  [✔️] now-playing-1.1.4-fat
  [✔️] optifabric-1.8.16
  [✔️] OptiFine_1.16.4_HD_U_G5
  [✔️] rer-2.1.3
  [✔️] RoughlyEnoughItems-5.8.8
  [✔️] shulkerboxtooltip-2.3.3+1.16.4
  [✔️] tweakeroo-fabric-1.16.4-0.10.0-dev.20201110.132827
  [✔️] Xaeros_Minimap_20.29.0_Fabric_1.16.4
  [✔️] XaerosWorldMap_1.11.4_Fabric_1.16.4

Tried searching up the issue and found threads concerning the always-tesselate-blocks and ambient-occlusion-mode config entries, and tried every combination mentioned to no avail.

Is there something I'm missing?

**Comment by Chocohead** [comment] 2021-01-09 03:45
Duplicate of #107

It's Blur which includes (and uses) Satin to apply its own shader when the game is paused.

**Closed as completed by Chocohead** 2021-01-09 03:45 UTC

**Comment by postal291** [comment] 2021-01-09 05:32
Thanks Chocohead :)
