### ISSUE TITLE
Optifabric & Origins Error

### ISSUE THREAD

**Issue by ttltrashmammal** [Chocohead/OptiFabric#310] opened 2021-07-12 05:17 UTC
Loading up the game with a fresh new installation of 1.17.1, Optifine, Fabric, Optifabric (the file uploaded 3 hours ago [4 hours ago] ), ModMenu and ShulkerBoxToolTip and it all worked out beautifully. I added Origins into the mix as I know it was a troublemaker before but it's needed for my server and this happened, same issue as before:

[00:11:51] [main/INFO]: Loading for game Minecraft 1.17.1
[00:11:51] [ForkJoinPool-1-worker-15/WARN]: Non-Fabric mod JAR at "C:\Users\dawns\AppData\Roaming\.minecraft\installations\optifabric.1.17.1\mods\preview_OptiFine_1.17.1_HD_U_G9_pre26.jar", ignoring
[00:11:51] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: origins conflicts with {optifabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:219) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:216) ~[fabric-loader-0.11.6.jar:?]
	... 5 more
[latest.log](https://github.com/Chocohead/OptiFabric/files/6798725/latest.log)

Unfortunately 1.0.2 of Origins fixed major bugs we were experiencing with our origins and we can't downgrade back to 1.0.0 as someone else suggested in a previous comment so I'm kinda at a loss. They just don't like one another I guess.

Edit (x2): I know it's not something you can necessarily control as Optifine isn't fully released yet, just something I wanted to make y'all aware of/ let others having the same issue know it's not just them haha)

**Comment by Chocohead** [comment] 2021-07-12 15:38
Duplicate of #281

**Closed as completed by Chocohead** 2021-07-12 15:38 UTC
