### ISSUE TITLE
Extreme Laggy with lithium.

### ISSUE THREAD

**Issue by KrisCris** [Chocohead/OptiFabric#18] opened 2020-09-01 04:36 UTC
MSPT rockets in a new world. I got 1000mspt after several minutes

Game version 1.16.2

Lithium 0.5.4,
Optifabric 1.4.2
OptiFine_1.16.2_HD_U_G3

PC Spec:
i7 7700hq
gtx 1060
Ram 16g 2666mhz

**Comment by Chocohead** [comment] 2020-09-01 23:48
This looks like it could be a duplicate of #17, is it world loading/chunk loading which is particularly slow or are you getting stalls even standing still?

**Comment by KrisCris** [comment] 2020-09-02 01:58
> is it world loading/chunk loading which is particularly slow

I am not able to load a NEW world because it's way too slow.

>or are you getting stalls even standing still?

Yes!

![2020-09-01_12 38 09](https://user-images.githubusercontent.com/38860226/91923401-dce60100-ed02-11ea-8e3d-87793951b7fd.png)

**Comment by KrisCris** [comment] 2020-09-02 02:04
My CPU usage bumps to 100%, and only 10 fps at the beginning. Then the TPS and FPS drops heavily even I was just standing still.

**Comment by KrisCris** [comment] 2020-09-02 02:05
#17 is also happening. I have to terminate the game in order to stop its save process as it takes too long.

**Comment by Chocohead** [comment] 2020-09-07 23:07
I've spun up a custom Lithium build to see if this resolves all the problems if you'd like to give it a try [here](https://jitpack.io/com/github/Chocohead/Lithium/1f8ed4d/Lithium-1f8ed4d.jar).

**Comment by KrisCris** [comment] 2020-09-08 03:39
> I've spun up a custom Lithium build to see if this resolves all the problems if you'd like to give it a try [here](https://jitpack.io/com/github/Chocohead/Lithium/1f8ed4d/Lithium-1f8ed4d.jar).

It works fine!

**Comment by onlyspxctre** [comment] 2020-10-13 19:28
Hey @Chocohead , can you update your custom version of Lithium for 1.16.3? Unless the lag issue has already been fixed (which I don't think it has, but I could be wrong,) stock Lithium cannot be used in conjunction with OptiFabric for 1.16.3.

**Comment by Chocohead** [comment] 2021-10-11 21:11
Duplicate of #17

**Closed as completed by Chocohead** 2021-10-11 21:11 UTC
Labels: Duplicate, Mod Compat
