### ISSUE TITLE
Issue with Optifabric

### ISSUE THREAD

**Issue by MangoTangoMan12** [Chocohead/OptiFabric#76] opened 2020-10-17 10:41 UTC
Hi, I wanted to use optifabric 1.6.4 with optifine 1.16.3, and it sends me this error:

" The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1 ", or it just sends the encountered an error Exit code: 0 message.

Can anyone help me? I'm a new user to optifabric, i have never used it before...

(P.S.: fabric version: 0.9.3, build 207 for version 1.16.3, fabric API 0.23.0, build 410 if you need these to help.)

**Comment by Chocohead** [comment] 2020-10-17 15:54
If you go into the `crash-reports` folder (which is a layer up from the `mods` folder where you added OptiFabric + Optifine), we could do with the newest file in there which should contain some more information for what went wrong.

**Comment by MangoTangoMan12** [comment] 2020-10-17 19:10
[crash-2020-10-16_08.17.30-client.txt](https://github.com/Chocohead/OptiFabric/files/5396363/crash-2020-10-16_08.17.30-client.txt)
Here, this is the latest crash report I have about the issue. If you need anything more, I would be more then happy to help!

**Comment by 0xfeeddeadbeef** [comment] 2020-10-17 19:23
This is a duplicate of #62 and #75. Update your hacked client.

**Comment by MangoTangoMan12** [comment] 2020-10-17 19:56
okay, thanks!

**Closed as completed** 2020-10-18 21:47 UTC
