### ISSUE TITLE
Incompatible mod set! Error while trying to run 1.19 optifabric

### ISSUE THREAD

**Issue by PepegaGMR** [Chocohead/OptiFabric#821] opened 2022-08-05 10:24 UTC
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Iris' (iris) 1.2.5 with any version that is compatible with:
		 - optifabric 1.13.8
	 - Replace mod 'Sodium' (sodium) 0.4.2+replaymod.rev.bfbc6de with any version that is compatible with:
		 - optifabric 1.13.8
Unmet dependency listing:
	 - Mod 'Iris' (iris) 1.2.5 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	 - Mod 'Sodium' (sodium) 0.4.2+replaymod.rev.bfbc6de is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.8!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Can someone tell me what to do? or perhaps which version of optifabric to use?

**Comment by topia** [comment] 2022-08-05 10:31
Duplicate of #797. we can't use optifabric with sodium/iris.

**Comment by PepegaGMR** [comment] 2022-08-05 10:32
> Duplicate of #797. we can't use optifabric with sodium/iris.

I've tried removing Sodium and Iris but it just ends up coming in as Error 1 :P

All the mods I use are
Fabric api
litematica 
minihud
modmenu
optifabric and Optifine
Replaymod

**Comment by topia** [comment] 2022-08-05 10:35
Could you attach the latest.log just after a crash (Error 1)? some of your install mod(s) aren't compatible with optifabric.

**Comment by PepegaGMR** [comment] 2022-08-05 10:38
If you want I can also copy the whole text if it doesn't work
[latest.log](https://github.com/Chocohead/OptiFabric/files/9267866/latest.log)

**Comment by topia** [comment] 2022-08-05 10:43
I think you encountered #814; optifabric currently isn't compatible with H9 versions. Unfortunately, the developer doesn't seem to have enough time to resolve it.

**Comment by PepegaGMR** [comment] 2022-08-05 10:45
So I'd reckon best thing to do is go onto H8 version?

**Comment by topia** [comment] 2022-08-05 10:46
I think, yes.

**Comment by PepegaGMR** [comment] 2022-08-05 10:47
I'll try it and let you know if it works.

It does indeed work like it should, Thank you!

**Closed as completed** 2022-08-05 10:50 UTC
