### ISSUE TITLE
Minecraft gets stuck in a loading loop with any version beyond OptiFine HD U H5 pre2

### ISSUE THREAD

**Issue by SleepyCatten** [Chocohead/OptiFabric#564] opened 2022-01-05 12:23 UTC
Good day,

Apologies in advance if I have not provided sufficient details here.

I am currently using:

Minecraft 1.18.1
Fabric 0.12.12 loader
OptiFabric 1.12.10
Optifine HD U H5 pre2

With pre2, the game loads and runs without any identified issues. However, if I update to pre3 or pre4, Minecraft becomes stuck in a loading loop at the "Mojang Studios" screen. The progress bar keeps trying to finish, then resets and continues loading in an infinite loop.

I've uploaded a copy of pre2, as it is no longer available on the OptiFine website. Pre3 and Pre4 are currently available on the OptiFine downloads page: https://optifine.net/downloads

[preview_OptiFine_1.18.1_HD_U_H5_pre2.jar.zip](https://github.com/Chocohead/OptiFabric/files/7814799/preview_OptiFine_1.18.1_HD_U_H5_pre2.jar.zip)

I am uncertain whether this is an OptiFabric bug or an OptiFine one. Please accept my apologies if it turns out to be an OptiFine one. I thought I should report, just in case.

Kind regards

**Comment by Nuanulla** [comment] 2022-01-05 19:44
Duplicate of #540

**Comment by Goofball2** [comment] 2022-03-21 02:40
> Good day,
> 
> 
> 
> Apologies in advance if I have not provided sufficient details here.
> 
> 
> 
> I am currently using:
> 
> 
> 
> Minecraft 1.18.1
> 
> Fabric 0.12.12 loader
> 
> OptiFabric 1.12.10
> 
> Optifine HD U H5 pre2
> 
> 
> 
> With pre2, the game loads and runs without any identified issues. However, if I update to pre3 or pre4, Minecraft becomes stuck in a loading loop at the "Mojang Studios" screen. The progress bar keeps trying to finish, then resets and continues loading in an infinite loop.
> 
> 
> 
> I've uploaded a copy of pre2, as it is no longer available on the OptiFine website. Pre3 and Pre4 are currently available on the OptiFine downloads page: https://optifine.net/downloads
> 
> 
> 
> [preview_OptiFine_1.18.1_HD_U_H5_pre2.jar.zip](https://github.com/Chocohead/OptiFabric/files/7814799/preview_OptiFine_1.18.1_HD_U_H5_pre2.jar.zip)
> 
> 
> 
> I am uncertain whether this is an OptiFabric bug or an OptiFine one. Please accept my apologies if it turns out to be an OptiFine one. I thought I should report, just in case.
> 
> 
> 
> Kind regards
> 
> 
> 
> 

Try using optifine 1.18.1 H4 instead of H5 as H5 is not supported

**Closed as completed** 2022-03-21 11:33 UTC
