### ISSUE TITLE
For some reason Optifabric conflicts with Origins

### ISSUE THREAD

**Issue by OneTrain73** [Chocohead/OptiFabric#289] opened 2021-06-28 21:07 UTC
They're completely different, and don't do anything similar. How does this conflict with Origins? Please explain I am confused

**Comment by CCCMTTT** [comment] 2021-06-29 08:28
I can second this, it crashes before launch

**Comment by Chocohead** [comment] 2021-07-10 14:39
Duplicate of #281

**Closed as completed by Chocohead** 2021-07-10 14:39 UTC
