### ISSUE TITLE
Crashes and font removed

### ISSUE THREAD

**Issue by CrystalloSaurus** [Chocohead/OptiFabric#1147] opened 2023-07-25 22:20 UTC
**Tried to get optifabric working and it just crashes my game when i try to play and the font is removed so its all rectangles.**

![image](https://github.com/Chocohead/OptiFabric/assets/117774618/b265bdbd-de10-4760-ba36-4d23363ddc17)

**Comment by AuroraDoesCode** [comment] 2023-07-25 23:00
Duplicate of #1123

**Closed as completed** 2023-07-25 23:15 UTC
