### ISSUE TITLE
Optifabric conflicts with Sodium

### ISSUE THREAD

**Issue by Dino730** [Chocohead/OptiFabric#298] opened 2021-07-05 14:42 UTC
Whenever I try to open the game with both of these mods in the folder this error message pops up:
![image_2021-07-05_154220](https://user-images.githubusercontent.com/86971417/124488302-98564680-dda7-11eb-8e5f-9d1538ccccd0.png)
I just want to know why this happens

**Comment by agGile** [comment] 2021-07-06 06:51
Thats probably because those 2 arent compatible, as i know those mods do the same so u cant run them together!!!
As it says in error  message "sodium conflicts with optifabric"

**Comment by joem-design** [comment] 2021-07-06 23:30
From the [Sodium Curseforge page](https://www.curseforge.com/minecraft/mc-mods/sodium): <b>Sodium and Optifine are incompatible with one another. You must pick one.</b>
Since Optifabric is only used to support optifine, you must be using optifine. If not, you don't need optifabric.

**Comment by Chocohead** [comment] 2021-07-10 14:42
Duplicate of #40, as mentioned there and above it's something which will simply never work with OptiFine.

**Closed as completed by Chocohead** 2021-07-10 14:42 UTC
