### ISSUE TITLE
OptiFabric could not find the Optifine jar in the mods folder

### ISSUE THREAD

**Issue by valentinegb** [Chocohead/OptiFabric#454] opened 2021-11-21 23:11 UTC
![image](https://user-images.githubusercontent.com/35977727/142782462-e215d8f2-fd9c-4167-9301-69478b5101e3.png)

I'm not really sure if I'm doing something wrong or if there's an error in the mod that I just need to wait to be resolved, but here's some info that might help:

**Minecraft:** 1.17.1
**Fabric Loader:** 0.11.7
**Mods:**
![image](https://user-images.githubusercontent.com/35977727/142782547-deef8b67-0efe-4efd-ac10-c6a97db25ecb.png)
**Windows 11 Pro:** 21H2 (22000.318)

**Comment by Chocohead** [comment] 2021-11-22 00:13
Duplicate of #374

This has (finally) been fixed with OptiFabric v1.11.22, you'll want to update to the (current) newest OptiFabric version [here](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3533297).

**Closed as completed by Chocohead** 2021-11-22 00:13 UTC

**Comment by Lenis-Felipe** [comment] 2022-08-14 14:58
i have 1.16.5 but  I get this error in developer console
-- OptiFabric --
Details:
	OptiFine jar designed for: ~~NULL~~
	OptiFine jar version: ~~NULL~~
	OptiFine jar status: Not found
	OptiFine remapped jar: ~~NULL~~
	OptiFabric error: OptiFabric could not find the Optifine jar in the mods folder:
