### ISSUE TITLE
Optifabric wants wrong version of Architectury.

### ISSUE THREAD

**Issue by The-HAX0R-31337** [Chocohead/OptiFabric#763] opened 2022-07-06 07:07 UTC
Optifabric wants a version of Architectury between 1.2.72 and 1.3.77, but the most recent version of it is 5.7.28. I have no idea how to fix it. I have attached my latest log.
[latest.log](https://github.com/Chocohead/OptiFabric/files/9052455/latest.log)

**Comment by topia** [comment] 2022-07-06 07:37
> [03:03:08] [main/INFO]: Loading Minecraft 1.19 with Quilt Loader 0.17.0

optifabric doesn't support the quilt-loader, and current dependency specification should be ok for the fabric-loader.

**Comment by The-HAX0R-31337** [comment] 2022-07-06 08:06
😔 Are there any plans to support quilt in the future?

**Comment by topia** [comment] 2022-07-06 08:46
Personally, I think, the quilt-loader should work with this "breaks" configuration because they provide "fabric-loader compatibility". Although the quilt-loader supports it, remain some problems: #751

**Comment by Sebyx1** [comment] 2022-07-07 02:00
Have the same problem, wait vor OptiFine Full Release :)

**Comment by Chocohead** [comment] 2022-07-23 23:44
Duplicate of #751

**Closed as completed by Chocohead** 2022-07-23 23:44 UTC
Labels: Duplicate
