### ISSUE TITLE
Optifabric 1.18 Crash

### ISSUE THREAD

**Issue by SoundEngineDevelopement** [Chocohead/OptiFabric#505] opened 2021-12-09 05:52 UTC
My game crashes.
This is the content of my mods folder:
soundphysics-0.4.1.jar
cloth-config-6.0.42-fabric.jar
fabric-api-0.44.0+1.18.jar
OptiFine_1.18_HD_U_H3.jar
optifabric-1.12.7.jar

Obviously i installed fabric and run minecraft via fabric, i use patrix resourcepack and seus ptgi shaderpack.
If i use only the sound engine i can play, when i add optifine and optifabric game crashs.

Error Code:
java.lang.runtimexpection: mixin transformation of net.minecraft.class_6850 failed
https://i.postimg.cc/Hxbt1LRJ/crash.png

I recorded what happens when starting minecraft with optifabric:
https://mega.nz/file/mgFUjbxb#lqnY76mzRicOvF2kG-QB7ph3nULenoNHoz6tSrLViqg

**Comment by SoundEngineDevelopement** [comment] 2021-12-09 06:00
I noticed Optifabric was last updated Dec 2, 2021while Optifine was last updated 06.12.2021.
Maybe the current version is outdated?

I recorded what happens when i launch fabric with optifabric, video takes only 15 seconds.
Video: https://mega.nz/file/mgFUjbxb#lqnY76mzRicOvF2kG-QB7ph3nULenoNHoz6tSrLViqg

**Comment by Squash00** [comment] 2021-12-09 06:18
Had the same issue earlier, try changing the Optifine version to the pre7 one, worked for me.

**Comment by SoundEngineDevelopement** [comment] 2021-12-09 08:33
> Had the same issue earlier, try changing the Optifine version to the pre7 one, worked for me.

Thanks fo confirming, i think i will wait for the next optifabric release instead.
Hopefully it will come soon.

**Comment by ghost** [comment] 2021-12-09 12:01
Optifabric needs an update to be compatible with the full 1.18 Optifine h3 release. For now, you have to use pre7, which works fine, or run optifine without fabric.

**Comment by storskegg** [comment] 2021-12-09 15:17
If it helps the developer(s), here's my [crash log](https://pastebin.com/1rzVXvwb).

**Comment by chris819t** [comment] 2021-12-09 16:41
I'm having the same issue as well. I even tried running it with the pre7 version of optifine and it still gives me the same issue.

**Comment by BastLast** [comment] 2021-12-09 17:31
I'm having the same issue, I'm going to try switching version and report if it still doesn't work :)

it worked

**Comment by AngelofWoe** [comment] 2021-12-09 20:00
This combination works just fine.
![image](https://user-images.githubusercontent.com/6075018/145466893-7ea791e8-dbdf-4d9f-85ed-94b12ac60454.png)

However, when updating from OptiFine 1.18 HD U H3 Pre 7 to the full release of 1.18 HD U H3, the client crashes, even if all mods other than Fabric API, OptiFine, and OptiFabric are removed.

[crash-2021-12-09_13.54.44-client.txt](https://github.com/Chocohead/OptiFabric/files/7688073/crash-2021-12-09_13.54.44-client.txt)

**Comment by Nuanulla** [comment] 2021-12-09 23:31
Duplicate of #499 and/or #497

**Comment by ValksMC** [comment] 2021-12-10 00:56
This is the content of my mods folder
![image](https://user-images.githubusercontent.com/95891981/145498806-6c517db1-2121-4cad-8a7e-bcaf84ecf0e4.png)
When I run it without optifine and optifabric it works fine, but when I add them the game chashes and gives me the error code: 0

**Comment by Cinder4198** [comment] 2021-12-10 02:18
I came across the same issue and I started using the Pre 7 version, but now it only crashes when I log onto hypixel for some reason.

edit: nevermind it was another mod

[crash-2021-12-09_20.14.08-client.txt](https://github.com/Chocohead/OptiFabric/files/7689654/crash-2021-12-09_20.14.08-client.txt)

**Closed as completed** 2021-12-13 23:59 UTC
