### ISSUE TITLE
So the sodium fabric mod isn't compatible with the optifabric mod?

### ISSUE THREAD

**Issue by Aw-lab** [Chocohead/OptiFabric#72] opened 2020-10-05 17:34 UTC
So when i found this mod, I was excited to test this with the sodium mod because Im looking to see what shaders I could run with it, but when i tryed launching the game, it came up with these error's:
![Capture](https://user-images.githubusercontent.com/72408079/95112855-7db74a00-070f-11eb-825a-a85614adc16f.PNG)
![Capture(1)](https://user-images.githubusercontent.com/72408079/95112862-7f810d80-070f-11eb-8e84-7417dc073161.PNG)

**Comment by Aw-lab** [comment] 2020-10-05 17:35
Im guessing they are incompatible for now?
Sodium mod: https://www.curseforge.com/minecraft/mc-mods/sodium

**Comment by IMS212** [comment] 2020-10-05 17:53
They will never be compatible, they completely change the rendering engine and accomplish a lot of similar things.

**Comment by Chocohead** [comment] 2020-10-05 21:57
Duplicate of #40, as mentioned there and above it's something which will simply never work with OptiFine.

**Closed as completed by Chocohead** 2020-10-05 21:57 UTC
