### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by vinnyg0621** [Chocohead/OptiFabric#83] opened 2020-10-29 19:20 UTC
![crash1](https://user-images.githubusercontent.com/57818441/97622176-23916800-19e1-11eb-94a8-e4e597ab30bb.PNG)

**Comment by vinnyg0621** [comment] 2020-10-29 19:25
the crash report:

[12:19:11] [main/INFO]: Loading for game Minecraft 1.16.3
[12:19:13] [ForkJoinPool-1-worker-2/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[12:19:13] [ForkJoinPool-1-worker-2/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[12:19:13] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[12:19:13] [ForkJoinPool-1-worker-1/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[12:19:13] [ForkJoinPool-1-worker-2/WARN]: Non-Fabric mod JAR at "C:\Users\vinny.DESKTOP-HD3PDS0\OneDrive\Desktop\Minecraft\OptiFabric 1.16\mods\preview_OptiFine_1.16.3_HD_U_G4_pre2.jar", ignoring
[12:19:13] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[12:19:13] [ForkJoinPool-1-worker-1/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[12:19:13] [ForkJoinPool-1-worker-2/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[12:19:13] [ForkJoinPool-1-worker-2/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[12:19:13] [ForkJoinPool-1-worker-3/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[12:19:13] [ForkJoinPool-1-worker-3/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[12:19:13] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: sodium conflicts with {optifabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:194) ~[fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.10.5+build.213.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:191) ~[fabric-loader-0.10.5+build.213.jar:?]
	... 5 more

**Comment by Chocohead** [comment] 2020-10-30 03:08
Duplicate of #40

**Closed as completed by Chocohead** 2020-10-30 03:08 UTC
