### ISSUE TITLE
1.18.2 plz

### ISSUE THREAD

**Issue by yeete183** [Chocohead/OptiFabric#619] opened 2022-03-05 00:30 UTC
i dont want glow swquids

**Comment by UnlimitedKaos** [comment] 2022-03-07 18:18
Duplicate of #618

**Comment by yeete183** [comment] 2022-03-07 20:22
am aware

**Comment by FrozenDragon0** [comment] 2022-03-08 01:00
> am aware

Then why did you open a 2nd issue?

**Comment by Skywalker8510** [comment] 2022-03-28 21:51
this can be closed now there is a 1.18.2 version on curseforge

**Closed as completed** 2022-03-29 06:45 UTC
