### ISSUE TITLE
Optifabric 1.12.6 isn't working with 1.18 for me ?

### ISSUE THREAD

**Issue by Littledrama2** [Chocohead/OptiFabric#479] opened 2021-12-01 05:04 UTC
For some reason, I have updated all of my mods to 1.18 because of the new update. When I try and load Minecraft with these mods, Minecraft says that there is a problem with loading Optifabric 1.12.6 with 1.18. Please can someone help !
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/95332523/144175117-bc885fa1-5b5c-41fb-af5f-206b9cb5e118.PNG">

**Comment by Potato22** [comment] 2021-12-01 05:14
Duplicate of #476

**Closed as completed** 2021-12-01 23:49 UTC
