### ISSUE TITLE
Optifabric and Origins mod are not compatible on the most recent versions

### ISSUE THREAD

**Issue by Amerdisiac** [Chocohead/OptiFabric#286] opened 2021-06-27 23:47 UTC
![image](https://user-images.githubusercontent.com/86577651/123563054-1a001000-d7bb-11eb-97bd-0ab0d98344dc.png)

**Comment by fayeispro** [comment] 2021-06-28 20:06
same, I also need help with this, it's really annoying

**Comment by Chocohead** [comment] 2021-07-10 14:39
Duplicate of #281

**Closed as completed by Chocohead** 2021-07-10 14:39 UTC
