### ISSUE TITLE
Conflicting with Sodium

### ISSUE THREAD

**Issue by TheSexyYeti** [Chocohead/OptiFabric#114] opened 2020-12-02 21:52 UTC
Newest version is conflicting with Sodium. It won't even load the game. It just crashes immediately.

**Comment by TheSexyYeti** [comment] 2020-12-02 21:54
Oop never mind. Just realised Sodium isn't even updated to the newest version.

**Comment by Titaniumtown** [comment] 2020-12-02 21:58
Optifabric doesn't work with sodium because they both replace/modify the rendering engine.

**Comment by IMS212** [comment] 2020-12-02 22:07
Sodium does work on the newest version, but it will never work with Optifabric/optifine.

**Comment by TheSexyYeti** [comment] 2020-12-02 22:54
Hmm good to know. Just curious. But are you ever gonna including shader support in sodium?. Sodium is the best mod I've seen to help with lag. But the only reason I wanted to use Optifine is to use Shaders.

**Comment by Titaniumtown** [comment] 2020-12-02 22:55
> But are you ever gonna including shader support in sodium?

Me lol? That is not sodium's goal.

**Comment by IMS212** [comment] 2020-12-03 05:08
Iris is an attempt to get optifine shaders working on fabric without optifine, and may eventually have sodium support, it’s still in an early state right now.

**Comment by Chocohead** [comment] 2020-12-04 16:25
Duplicate of #40

**Closed as completed by Chocohead** 2020-12-04 16:25 UTC
